In [1]:
from datetime import datetime, timedelta
from email.utils import parsedate_to_datetime
from urllib.parse import quote_plus
from zoneinfo import ZoneInfo

import feedparser
import requests

In [ ]:
SOURCE_CANDIDATES = {
    # 1순위: 미국 증시/금융 전문
    "finance.yahoo.com": "Yahoo Finance",
    "cnbc.com": "CNBC",
    "marketwatch.com": "MarketWatch",
    "barrons.com": "Barron's",

    # 2순위: 경제/비즈니스 종합
    "fortune.com": "Fortune",
    "forbes.com": "Forbes",
    "businessinsider.com": "Business Insider",
    "cnn.com": "CNN Business",
    "foxbusiness.com": "Fox Business",
    "apnews.com": "Associated Press",

    # 3순위: 투자 전문
    "benzinga.com": "Benzinga",
    "thestreet.com": "TheStreet",
    "fool.com": "The Motley Fool",
    "seekingalpha.com": "Seeking Alpha",
    "investing.com": "Investing.com",
    "zacks.com": "Zacks",

    # 접근 제한 가능성이 높은 곳도 비교용으로 테스트
    "bloomberg.com": "Bloomberg",
    "wsj.com": "Wall Street Journal",
    "ft.com": "Financial Times",
    "reuters.com": "Reuters",
}


TEST_QUERIES = [
    "stock market",
    "Wall Street",
    "Federal Reserve",
    "earnings",
    "NVIDIA",
]

START_DATE = "2026-10-20"
END_DATE = "2026-10-21"

NEWS_TIMEZONE = ZoneInfo("America/New_York")

In [3]:
def date_range(start_date, end_date):
    start = datetime.strptime(start_date, "%Y-%m-%d").date()
    end = datetime.strptime(end_date, "%Y-%m-%d").date()

    current = start

    while current <= end:
        yield current
        current += timedelta(days=1)

In [4]:
def build_google_news_rss_url(query, source, target_date):
    """
    target_date 주변을 조금 넓게 검색한 뒤
    실제 날짜 필터링은 Python에서 다시 수행합니다.
    """

    search_after = target_date - timedelta(days=1)
    search_before = target_date + timedelta(days=1)

    search_query = (
        f'"{query}" '
        f'site:{source} '
        f'after:{search_after.isoformat()} '
        f'before:{search_before.isoformat()}'
    )

    encoded_query = quote_plus(search_query)

    url = (
        "https://news.google.com/rss/search"
        f"?q={encoded_query}"
        "&hl=en-US"
        "&gl=US"
        "&ceid=US:en"
    )

    return url, search_query

In [5]:
def search_google_news(query, source, target_date):
    url, search_query = build_google_news_rss_url(
        query=query,
        source=source,
        target_date=target_date,
    )

    response = requests.get(
        url,
        headers={
            "User-Agent": "Mozilla/5.0"
        },
        timeout=15,
    )

    response.raise_for_status()

    feed = feedparser.parse(response.content)

    articles = []

    for entry in feed.entries:

        published_raw = entry.get("published")

        if not published_raw:
            continue

        try:
            published_dt = parsedate_to_datetime(published_raw)

            # RSS 시간은 보통 GMT이므로
            # 미국 동부시간으로 변환
            published_et = published_dt.astimezone(NEWS_TIMEZONE)

        except Exception:
            continue

        # 우리가 원하는 미국 동부시간 날짜와 정확히 일치하는지 검사
        if published_et.date() != target_date:
            continue

        rss_source = None

        if hasattr(entry, "source"):
            rss_source = entry.source.get("title")

        articles.append({
            "query": query,
            "requested_source": source,

            "title": entry.get("title"),
            "google_news_url": entry.get("link"),

            "source": rss_source,

            "published_raw": published_raw,
            "published_at": published_dt.isoformat(),
            "published_at_et": published_et.isoformat(),

            "target_date": target_date.isoformat(),

            "search_query": search_query,
        })

    return articles

In [6]:
def collect_google_news(
    search_terms,
    sources,
    start_date,
    end_date,
):
    all_articles = []

    dates = list(date_range(start_date, end_date))

    total = (
        len(search_terms)
        * len(sources)
        * len(dates)
    )

    count = 0

    for target_date in dates:

        for query in search_terms:

            for source in sources:
                count += 1

                print(
                    f"[{count}/{total}] "
                    f"{target_date} | "
                    f"{source} | "
                    f"{query}"
                )

                try:
                    articles = search_google_news(
                        query=query,
                        source=source,
                        target_date=target_date,
                    )

                    print(
                        f"    → {len(articles)} articles"
                    )

                    all_articles.extend(articles)

                except Exception as e:
                    print(
                        f"    → ERROR: "
                        f"{type(e).__name__}: {e}"
                    )

    return all_articles

In [7]:
articles = collect_google_news(
    search_terms=TEST_QUERIES,
    sources=SOURCE_CANDIDATES,
    start_date=START_DATE,
    end_date=END_DATE,
)

len(articles)

[1/200] 2026-10-20 | finance.yahoo.com | stock market
    → 66 articles
[2/200] 2026-10-20 | cnbc.com | stock market
    → 36 articles
[3/200] 2026-10-20 | marketwatch.com | stock market
    → 28 articles
[4/200] 2026-10-20 | barrons.com | stock market
    → 24 articles
[5/200] 2026-10-20 | fortune.com | stock market
    → 4 articles
[6/200] 2026-10-20 | forbes.com | stock market
    → 2 articles
[7/200] 2026-10-20 | businessinsider.com | stock market
    → 42 articles
[8/200] 2026-10-20 | cnn.com | stock market
    → 3 articles
[9/200] 2026-10-20 | foxbusiness.com | stock market
    → 7 articles
[10/200] 2026-10-20 | apnews.com | stock market
    → 2 articles
[11/200] 2026-10-20 | benzinga.com | stock market
    → 62 articles
[12/200] 2026-10-20 | thestreet.com | stock market
    → 41 articles
[13/200] 2026-10-20 | fool.com | stock market
    → 72 articles
[14/200] 2026-10-20 | seekingalpha.com | stock market
    → 39 articles
[15/200] 2026-10-20 | investing.com | stock market
    → 59 articles
[16/200] 2026-10-20 | zacks.com | stock market
    → 47 articles
[17/200] 2026-10-20 | bloomberg.com | stock market
    → 36 articles
[18/200] 2026-10-20 | wsj.com | stock market
    → 25 articles
[19/200] 2026-10-20 | ft.com | stock market
    → 16 articles
[20/200] 2026-10-20 | reuters.com | stock market
    → 13 articles
[21/200] 2026-10-20 | finance.yahoo.com | Wall Street
    → 61 articles
[22/200] 2026-10-20 | cnbc.com | Wall Street
    → 32 articles
[23/200] 2026-10-20 | marketwatch.com | Wall Street
    → 13 articles
[24/200] 2026-10-20 | barrons.com | Wall Street
    → 52 articles
[25/200] 2026-10-20 | fortune.com | Wall Street
    → 15 articles
[26/200] 2026-10-20 | forbes.com | Wall Street
    → 11 articles
[27/200] 2026-10-20 | businessinsider.com | Wall Street
    → 49 articles
[28/200] 2026-10-20 | cnn.com | Wall Street
    → 53 articles
[29/200] 2026-10-20 | foxbusiness.com | Wall Street
    → 4 articles
[30/200] 2026-10-20 | apnews.com | Wall Street
    → 17 articles
[31/200] 2026-10-20 | benzinga.com | Wall Street
    → 59 articles
[32/200] 2026-10-20 | thestreet.com | Wall Street
    → 42 articles
[33/200] 2026-10-20 | fool.com | Wall Street
    → 46 articles
[34/200] 2026-10-20 | seekingalpha.com | Wall Street
    → 55 articles
[35/200] 2026-10-20 | investing.com | Wall Street
    → 78 articles
[36/200] 2026-10-20 | zacks.com | Wall Street
    → 58 articles
[37/200] 2026-10-20 | bloomberg.com | Wall Street
    → 52 articles
[38/200] 2026-10-20 | wsj.com | Wall Street
    → 83 articles
[39/200] 2026-10-20 | ft.com | Wall Street
    → 19 articles
[40/200] 2026-10-20 | reuters.com | Wall Street
    → 49 articles
[41/200] 2026-10-20 | finance.yahoo.com | Federal Reserve
    → 55 articles
[42/200] 2026-10-20 | cnbc.com | Federal Reserve
    → 10 articles
[43/200] 2026-10-20 | marketwatch.com | Federal Reserve
    → 32 articles
[44/200] 2026-10-20 | barrons.com | Federal Reserve
    → 2 articles
[45/200] 2026-10-20 | fortune.com | Federal Reserve
    → 12 articles
[46/200] 2026-10-20 | forbes.com | Federal Reserve
    → 10 articles
[47/200] 2026-10-20 | businessinsider.com | Federal Reserve
    → 7 articles
[48/200] 2026-10-20 | cnn.com | Federal Reserve
    → 0 articles
[49/200] 2026-10-20 | foxbusiness.com | Federal Reserve
    → 0 articles
[50/200] 2026-10-20 | apnews.com | Federal Reserve
    → 0 articles
[51/200] 2026-10-20 | benzinga.com | Federal Reserve
    → 14 articles
[52/200] 2026-10-20 | thestreet.com | Federal Reserve
    → 9 articles
[53/200] 2026-10-20 | fool.com | Federal Reserve
    → 27 articles
[54/200] 2026-10-20 | seekingalpha.com | Federal Reserve
    → 38 articles
[55/200] 2026-10-20 | investing.com | Federal Reserve
    → 41 articles
[56/200] 2026-10-20 | zacks.com | Federal Reserve
    → 1 articles
[57/200] 2026-10-20 | bloomberg.com | Federal Reserve
    → 8 articles
[58/200] 2026-10-20 | wsj.com | Federal Reserve
    → 12 articles
[59/200] 2026-10-20 | ft.com | Federal Reserve
    → 14 articles
[60/200] 2026-10-20 | reuters.com | Federal Reserve
    → 22 articles
[61/200] 2026-10-20 | finance.yahoo.com | earnings
    → 63 articles
[62/200] 2026-10-20 | cnbc.com | earnings
    → 61 articles
[63/200] 2026-10-20 | marketwatch.com | earnings
    → 71 articles
[64/200] 2026-10-20 | barrons.com | earnings
    → 46 articles
[65/200] 2026-10-20 | fortune.com | earnings
    → 94 articles
[66/200] 2026-10-20 | forbes.com | earnings
    → 29 articles
[67/200] 2026-10-20 | businessinsider.com | earnings
    → 62 articles
[68/200] 2026-10-20 | cnn.com | earnings
    → 37 articles
[69/200] 2026-10-20 | foxbusiness.com | earnings
    → 4 articles
[70/200] 2026-10-20 | apnews.com | earnings
    → 2 articles
[71/200] 2026-10-20 | benzinga.com | earnings
    → 67 articles
[72/200] 2026-10-20 | thestreet.com | earnings
    → 49 articles
[73/200] 2026-10-20 | fool.com | earnings
    → 65 articles
[74/200] 2026-10-20 | seekingalpha.com | earnings
    → 73 articles
[75/200] 2026-10-20 | investing.com | earnings
    → 81 articles
[76/200] 2026-10-20 | zacks.com | earnings
    → 53 articles
[77/200] 2026-10-20 | bloomberg.com | earnings
    → 64 articles
[78/200] 2026-10-20 | wsj.com | earnings
    → 64 articles
[79/200] 2026-10-20 | ft.com | earnings
    → 65 articles
[80/200] 2026-10-20 | reuters.com | earnings
    → 51 articles
[81/200] 2026-10-20 | finance.yahoo.com | NVIDIA
    → 51 articles
[82/200] 2026-10-20 | cnbc.com | NVIDIA
    → 17 articles
[83/200] 2026-10-20 | marketwatch.com | NVIDIA
    → 19 articles
[84/200] 2026-10-20 | barrons.com | NVIDIA
    → 35 articles
[85/200] 2026-10-20 | fortune.com | NVIDIA
    → 23 articles
[86/200] 2026-10-20 | forbes.com | NVIDIA
    → 22 articles
[87/200] 2026-10-20 | businessinsider.com | NVIDIA
    → 22 articles
[88/200] 2026-10-20 | cnn.com | NVIDIA
    → 15 articles
[89/200] 2026-10-20 | foxbusiness.com | NVIDIA
    → 0 articles
[90/200] 2026-10-20 | apnews.com | NVIDIA
    → 0 articles
[91/200] 2026-10-20 | benzinga.com | NVIDIA
    → 36 articles
[92/200] 2026-10-20 | thestreet.com | NVIDIA
    → 26 articles
[93/200] 2026-10-20 | fool.com | NVIDIA
    → 57 articles
[94/200] 2026-10-20 | seekingalpha.com | NVIDIA
    → 50 articles
[95/200] 2026-10-20 | investing.com | NVIDIA
    → 37 articles
[96/200] 2026-10-20 | zacks.com | NVIDIA
    → 73 articles
[97/200] 2026-10-20 | bloomberg.com | NVIDIA
    → 56 articles
[98/200] 2026-10-20 | wsj.com | NVIDIA
    → 14 articles
[99/200] 2026-10-20 | ft.com | NVIDIA
    → 20 articles
[100/200] 2026-10-20 | reuters.com | NVIDIA
    → 48 articles
[101/200] 2026-10-21 | finance.yahoo.com | stock market
    → 69 articles
[102/200] 2026-10-21 | cnbc.com | stock market
    → 47 articles
[103/200] 2026-10-21 | marketwatch.com | stock market
    → 27 articles
[104/200] 2026-10-21 | barrons.com | stock market
    → 45 articles
[105/200] 2026-10-21 | fortune.com | stock market
    → 4 articles
[106/200] 2026-10-21 | forbes.com | stock market
    → 6 articles
[107/200] 2026-10-21 | businessinsider.com | stock market
    → 33 articles
[108/200] 2026-10-21 | cnn.com | stock market
    → 3 articles
[109/200] 2026-10-21 | foxbusiness.com | stock market
    → 5 articles
[110/200] 2026-10-21 | apnews.com | stock market
    → 5 articles
[111/200] 2026-10-21 | benzinga.com | stock market
    → 50 articles
[112/200] 2026-10-21 | thestreet.com | stock market
    → 48 articles
[113/200] 2026-10-21 | fool.com | stock market
    → 72 articles
[114/200] 2026-10-21 | seekingalpha.com | stock market
    → 35 articles
[115/200] 2026-10-21 | investing.com | stock market
    → 35 articles
[116/200] 2026-10-21 | zacks.com | stock market
    → 30 articles
[117/200] 2026-10-21 | bloomberg.com | stock market
    → 28 articles
[118/200] 2026-10-21 | wsj.com | stock market
    → 14 articles
[119/200] 2026-10-21 | ft.com | stock market
    → 12 articles
[120/200] 2026-10-21 | reuters.com | stock market
    → 13 articles
[121/200] 2026-10-21 | finance.yahoo.com | Wall Street
    → 68 articles
[122/200] 2026-10-21 | cnbc.com | Wall Street
    → 23 articles
[123/200] 2026-10-21 | marketwatch.com | Wall Street
    → 18 articles
[124/200] 2026-10-21 | barrons.com | Wall Street
    → 52 articles
[125/200] 2026-10-21 | fortune.com | Wall Street
    → 15 articles
[126/200] 2026-10-21 | forbes.com | Wall Street
    → 18 articles
[127/200] 2026-10-21 | businessinsider.com | Wall Street
    → 47 articles
[128/200] 2026-10-21 | cnn.com | Wall Street
    → 42 articles
[129/200] 2026-10-21 | foxbusiness.com | Wall Street
    → 5 articles
[130/200] 2026-10-21 | apnews.com | Wall Street
    → 7 articles
[131/200] 2026-10-21 | benzinga.com | Wall Street
    → 58 articles
[132/200] 2026-10-21 | thestreet.com | Wall Street
    → 41 articles
[133/200] 2026-10-21 | fool.com | Wall Street
    → 60 articles
[134/200] 2026-10-21 | seekingalpha.com | Wall Street
    → 44 articles
[135/200] 2026-10-21 | investing.com | Wall Street
    → 46 articles
[136/200] 2026-10-21 | zacks.com | Wall Street
    → 48 articles
[137/200] 2026-10-21 | bloomberg.com | Wall Street
    → 50 articles
[138/200] 2026-10-21 | wsj.com | Wall Street
    → 67 articles
[139/200] 2026-10-21 | ft.com | Wall Street
    → 16 articles
[140/200] 2026-10-21 | reuters.com | Wall Street
    → 50 articles
[141/200] 2026-10-21 | finance.yahoo.com | Federal Reserve
    → 39 articles
[142/200] 2026-10-21 | cnbc.com | Federal Reserve
    → 4 articles
[143/200] 2026-10-21 | marketwatch.com | Federal Reserve
    → 25 articles
[144/200] 2026-10-21 | barrons.com | Federal Reserve
    → 3 articles
[145/200] 2026-10-21 | fortune.com | Federal Reserve
    → 11 articles
[146/200] 2026-10-21 | forbes.com | Federal Reserve
    → 13 articles
[147/200] 2026-10-21 | businessinsider.com | Federal Reserve
    → 12 articles
[148/200] 2026-10-21 | cnn.com | Federal Reserve
    → 1 articles
[149/200] 2026-10-21 | foxbusiness.com | Federal Reserve
    → 1 articles
[150/200] 2026-10-21 | apnews.com | Federal Reserve
    → 3 articles
[151/200] 2026-10-21 | benzinga.com | Federal Reserve
    → 9 articles
[152/200] 2026-10-21 | thestreet.com | Federal Reserve
    → 8 articles
[153/200] 2026-10-21 | fool.com | Federal Reserve
    → 17 articles
[154/200] 2026-10-21 | seekingalpha.com | Federal Reserve
    → 36 articles
[155/200] 2026-10-21 | investing.com | Federal Reserve
    → 45 articles
[156/200] 2026-10-21 | zacks.com | Federal Reserve
    → 2 articles
[157/200] 2026-10-21 | bloomberg.com | Federal Reserve
    → 18 articles
[158/200] 2026-10-21 | wsj.com | Federal Reserve
    → 12 articles
[159/200] 2026-10-21 | ft.com | Federal Reserve
    → 13 articles
[160/200] 2026-10-21 | reuters.com | Federal Reserve
    → 11 articles
[161/200] 2026-10-21 | finance.yahoo.com | earnings
    → 65 articles
[162/200] 2026-10-21 | cnbc.com | earnings
    → 53 articles
[163/200] 2026-10-21 | marketwatch.com | earnings
    → 31 articles
[164/200] 2026-10-21 | barrons.com | earnings
    → 54 articles
[165/200] 2026-10-21 | fortune.com | earnings
    → 15 articles
[166/200] 2026-10-21 | forbes.com | earnings
    → 27 articles
[167/200] 2026-10-21 | businessinsider.com | earnings
    → 55 articles
[168/200] 2026-10-21 | cnn.com | earnings
    → 36 articles
[169/200] 2026-10-21 | foxbusiness.com | earnings
    → 11 articles
[170/200] 2026-10-21 | apnews.com | earnings
    → 8 articles
[171/200] 2026-10-21 | benzinga.com | earnings
    → 51 articles
[172/200] 2026-10-21 | thestreet.com | earnings
    → 47 articles
[173/200] 2026-10-21 | fool.com | earnings
    → 54 articles
[174/200] 2026-10-21 | seekingalpha.com | earnings
    → 52 articles
[175/200] 2026-10-21 | investing.com | earnings
    → 77 articles
[176/200] 2026-10-21 | zacks.com | earnings
    → 49 articles
[177/200] 2026-10-21 | bloomberg.com | earnings
    → 48 articles
[178/200] 2026-10-21 | wsj.com | earnings
    → 43 articles
[179/200] 2026-10-21 | ft.com | earnings
    → 50 articles
[180/200] 2026-10-21 | reuters.com | earnings
    → 47 articles
[181/200] 2026-10-21 | finance.yahoo.com | NVIDIA
    → 67 articles
[182/200] 2026-10-21 | cnbc.com | NVIDIA
    → 26 articles
[183/200] 2026-10-21 | marketwatch.com | NVIDIA
    → 22 articles
[184/200] 2026-10-21 | barrons.com | NVIDIA
    → 37 articles
[185/200] 2026-10-21 | fortune.com | NVIDIA
    → 11 articles
[186/200] 2026-10-21 | forbes.com | NVIDIA
    → 18 articles
[187/200] 2026-10-21 | businessinsider.com | NVIDIA
    → 55 articles
[188/200] 2026-10-21 | cnn.com | NVIDIA
    → 8 articles
[189/200] 2026-10-21 | foxbusiness.com | NVIDIA
    → 2 articles
[190/200] 2026-10-21 | apnews.com | NVIDIA
    → 3 articles
[191/200] 2026-10-21 | benzinga.com | NVIDIA
    → 55 articles
[192/200] 2026-10-21 | thestreet.com | NVIDIA
    → 19 articles
[193/200] 2026-10-21 | fool.com | NVIDIA
    → 59 articles
[194/200] 2026-10-21 | seekingalpha.com | NVIDIA
    → 43 articles
[195/200] 2026-10-21 | investing.com | NVIDIA
    → 87 articles
[196/200] 2026-10-21 | zacks.com | NVIDIA
    → 74 articles
[197/200] 2026-10-21 | bloomberg.com | NVIDIA
    → 56 articles
[198/200] 2026-10-21 | wsj.com | NVIDIA
    → 10 articles
[199/200] 2026-10-21 | ft.com | NVIDIA
    → 29 articles
[200/200] 2026-10-21 | reuters.com | NVIDIA
    → 47 articles

6748

In [8]:
def remove_duplicates(articles):
    unique_articles = {}

    for article in articles:

        key = (
            article["title"],
            article["source"],
            article["published_at"],
        )

        if key not in unique_articles:
            unique_articles[key] = article

        else:
            # 같은 기사가 여러 검색어에 걸린 경우
            existing = unique_articles[key]

            if "matched_queries" not in existing:
                existing["matched_queries"] = [
                    existing["query"]
                ]

            if article["query"] not in existing["matched_queries"]:
                existing["matched_queries"].append(
                    article["query"]
                )

    return list(unique_articles.values())

In [9]:
articles = remove_duplicates(articles)

print(f"중복 제거 후: {len(articles)}")

중복 제거 후: 4942

In [18]:
#pip install -U googlenewsdecoder

In [10]:
from googlenewsdecoder import gnews_decoder_async


async def resolve_original_urls(
    articles,
    batch_size=50,
    concurrency=6,
):
    resolved_articles = []

    for start in range(0, len(articles), batch_size):
        batch = articles[start:start + batch_size]

        google_urls = [
            article["google_news_url"]
            for article in batch
        ]

        try:
            results = await gnews_decoder_async(
                google_urls,
                interval=0.2,
                timeout=15.0,
                concurrency=concurrency,
            )

        except Exception as e:
            # 배치 전체 실패
            for article in batch:
                resolved_articles.append({
                    **article,
                    "original_url": None,
                    "resolve_status": "ERROR",
                    "resolve_error": f"{type(e).__name__}: {e}",
                })

            continue

        for article, result in zip(batch, results):

            if result.get("success"):
                resolved_articles.append({
                    **article,
                    "original_url": result["decoded_url"],
                    "resolve_status": "SUCCESS",
                    "resolve_error": None,
                })

            else:
                resolved_articles.append({
                    **article,
                    "original_url": None,
                    "resolve_status": "FAILED",
                    "resolve_error": result.get("message"),
                })

    return resolved_articles

In [11]:
resolved_articles = await resolve_original_urls(
    articles,
    batch_size=50,
    concurrency=6,
)

In [12]:
for article in resolved_articles[:10]:
    print(
        article["resolve_status"],
        "|",
        article["original_url"]
    )

SUCCESS | https://finance.yahoo.com/healthcare/articles/moderna-jumps-7-while-melanoma-175326781.html
SUCCESS | https://finance.yahoo.com/news/paul-tudor-jones-makes-chilling-154500005.html
SUCCESS | https://finance.yahoo.com/economy/article/advice-for-home-sellers-if-youre-trying-to-time-the-market-you-cant-123147322.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/stock-market-today-oct-20-220001509.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/stock-market-today-oct-20-213835202.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/united-parcel-ups-beats-stock-210006260.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/qualcomm-qcom-beats-stock-market-204505184.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/warren-buffett-issuing-stark-warning-082000676.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/stock-market-today-oct-20-210942173.html
SUCCESS | https://finance.yahoo.com/markets/stocks/articles/stock-market-today-oct-20-211901821.html

In [13]:
for i in resolved_articles[:3]:
    print(i)

{'query': 'stock market', 'requested_source': 'finance.yahoo.com', 'title': 'Moderna Jumps 7% While Melanoma Vaccine Data Looms; Bristol Myers Squibb Rises 5%, Pfizer Advances 2% - Yahoo Finance', 'google_news_url': 'https://news.google.com/rss/articles/CBMilgFBVV95cUxOMlg3YXlXcTUzYUxzbXRkSlRJUUVTRXJ5LW1KMS1GZ1J1SDVXR1BIdF9TM2pjaFljUXZUdHZORm50YjhaVnRNSXNvQ1JYLXhKRGExbk1YeE9GZWxoeXg0aktmZW1vbE5mTXA3a1RhRXZWYlVUbFJZbnE1VVFsVTVyRFZwazUxYS05MVdhU082NE9pejdYNXc?oc=5', 'source': 'Yahoo Finance', 'published_raw': 'Tue, 20 Oct 2026 17:53:26 GMT', 'published_at': '2026-10-20T17:53:26+00:00', 'published_at_et': '2026-10-20T13:53:26-04:00', 'target_date': '2026-10-20', 'search_query': '"stock market" site:finance.yahoo.com after:2026-10-19 before:2026-10-21', 'original_url': 'https://finance.yahoo.com/healthcare/articles/moderna-jumps-7-while-melanoma-175326781.html', 'resolve_status': 'SUCCESS', 'resolve_error': None}
{'query': 'stock market', 'requested_source': 'finance.yahoo.com', 'title': 'Paul Tudor Jones makes chilling 2027 US stock market call: ‘I’ll be short the whole year.’ Is your nest egg at risk? - Yahoo Finance', 'google_news_url': 'https://news.google.com/rss/articles/CBMigwFBVV95cUxPX0pUVWpZVTd1WEM5YkNfUUEtZ3Z1TWV3YlpPY2cxU2FCaHB0djQ4MGp6TXNnUC0tTzRnRkxKSU1JQlVYTzAwOGE5YjdPek9HbExmdEg0a0FFNHhFU1o4czIwVG5YNFpYTWpnUWctS1IwYWNlaFF1dXRvYkFWZmpzczk2VQ?oc=5', 'source': 'Yahoo Finance', 'published_raw': 'Tue, 20 Oct 2026 15:45:00 GMT', 'published_at': '2026-10-20T15:45:00+00:00', 'published_at_et': '2026-10-20T11:45:00-04:00', 'target_date': '2026-10-20', 'search_query': '"stock market" site:finance.yahoo.com after:2026-10-19 before:2026-10-21', 'original_url': 'https://finance.yahoo.com/news/paul-tudor-jones-makes-chilling-154500005.html', 'resolve_status': 'SUCCESS', 'resolve_error': None}
{'query': 'stock market', 'requested_source': 'finance.yahoo.com', 'title': "Advice for home sellers: 'If you're trying to time the market, you can't' - Yahoo Finance", 'google_news_url': 'https://news.google.com/rss/articles/CBMiwgFBVV95cUxQZmlNRldwTzNrUC1UaExkcHhGQmN3UDUzc0NEWmlqVWNBMGdFZ3dVVkVOS0VSaE9mQWY0Tzl0NC1aWmVYbGRzWU84cWthNzNHa3Y5TzlYUWREMTRXWllGLWlwaGFWekZhR1RwZXFsdHg3UnJoTVY2SUI1MWp6VWxPaHhEYjZJMnVSLS1JUUctZWNaZEVjdGp2SU50ODdjQ2RGb044a292b3A4VEY5b1BQWkE2V3ZFa3RGblM2eGtjWVFzUQ?oc=5', 'source': 'Yahoo Finance', 'published_raw': 'Tue, 20 Oct 2026 12:31:47 GMT', 'published_at': '2026-10-20T12:31:47+00:00', 'published_at_et': '2026-10-20T08:31:47-04:00', 'target_date': '2026-10-20', 'search_query': '"stock market" site:finance.yahoo.com after:2026-10-19 before:2026-10-21', 'original_url': 'https://finance.yahoo.com/economy/article/advice-for-home-sellers-if-youre-trying-to-time-the-market-you-cant-123147322.html', 'resolve_status': 'SUCCESS', 'resolve_error': None}

In [14]:
import random
import requests
import pandas as pd

from collections import defaultdict
from trafilatura import extract

In [15]:
MIN_TEST_ARTICLES = 5
PASS_RATE = 0.8

In [16]:
def classify_source(total, success):
    if total < MIN_TEST_ARTICLES:
        return "INSUFFICIENT_SAMPLE"

    success_rate = success / total

    if success_rate >= 0.8:
        return "USABLE"

    if success_rate >= 0.5:
        return "UNSTABLE"

    return "NOT_USABLE"

In [17]:
def sample_articles_for_test(
    resolved_articles,
    per_query=10,
    seed=42,
):
    groups = defaultdict(list)

    # source × query별 그룹 생성
    for article in resolved_articles:
        source = article.get("requested_source")
        query = article.get("query")
        url = article.get("original_url")

        if not source or not query or not url:
            continue

        groups[(source, query)].append(article)

    rng = random.Random(seed)

    sampled_articles = []

    for (source, query), articles in groups.items():

        # original_url 기준 중복 제거
        unique = {}

        for article in articles:
            url = article["original_url"]

            if url not in unique:
                unique[url] = article

        candidates = list(unique.values())

        # 최대 10개 랜덤 추출
        if len(candidates) > per_query:
            candidates = rng.sample(
                candidates,
                per_query,
            )

        sampled_articles.extend(candidates)

        print(
            f"{source:25s} | "
            f"{query:20s} | "
            f"{len(candidates)}개"
        )

    return sampled_articles

In [18]:
test_articles = sample_articles_for_test(
    resolved_articles,
    per_query=10,
    seed=42,
)

print()
print(f"총 테스트 기사 수: {len(test_articles)}")

finance.yahoo.com         | stock market         | 10개
cnbc.com                  | stock market         | 10개
marketwatch.com           | stock market         | 10개
barrons.com               | stock market         | 10개
fortune.com               | stock market         | 8개
forbes.com                | stock market         | 8개
businessinsider.com       | stock market         | 10개
cnn.com                   | stock market         | 6개
foxbusiness.com           | stock market         | 10개
apnews.com                | stock market         | 7개
benzinga.com              | stock market         | 10개
thestreet.com             | stock market         | 10개
fool.com                  | stock market         | 10개
seekingalpha.com          | stock market         | 10개
investing.com             | stock market         | 10개
zacks.com                 | stock market         | 10개
bloomberg.com             | stock market         | 10개
wsj.com                   | stock market         | 10개
ft.com                    | stock market         | 10개
reuters.com               | stock market         | 10개
finance.yahoo.com         | Wall Street          | 10개
cnbc.com                  | Wall Street          | 10개
marketwatch.com           | Wall Street          | 10개
barrons.com               | Wall Street          | 10개
fortune.com               | Wall Street          | 10개
forbes.com                | Wall Street          | 10개
businessinsider.com       | Wall Street          | 10개
cnn.com                   | Wall Street          | 10개
foxbusiness.com           | Wall Street          | 7개
apnews.com                | Wall Street          | 10개
benzinga.com              | Wall Street          | 10개
thestreet.com             | Wall Street          | 10개
fool.com                  | Wall Street          | 10개
seekingalpha.com          | Wall Street          | 10개
investing.com             | Wall Street          | 10개
zacks.com                 | Wall Street          | 10개
bloomberg.com             | Wall Street          | 10개
wsj.com                   | Wall Street          | 10개
ft.com                    | Wall Street          | 10개
reuters.com               | Wall Street          | 10개
finance.yahoo.com         | Federal Reserve      | 10개
cnbc.com                  | Federal Reserve      | 10개
marketwatch.com           | Federal Reserve      | 10개
barrons.com               | Federal Reserve      | 1개
fortune.com               | Federal Reserve      | 10개
forbes.com                | Federal Reserve      | 10개
businessinsider.com       | Federal Reserve      | 10개
benzinga.com              | Federal Reserve      | 10개
thestreet.com             | Federal Reserve      | 3개
fool.com                  | Federal Reserve      | 10개
seekingalpha.com          | Federal Reserve      | 10개
investing.com             | Federal Reserve      | 10개
zacks.com                 | Federal Reserve      | 3개
bloomberg.com             | Federal Reserve      | 10개
wsj.com                   | Federal Reserve      | 10개
ft.com                    | Federal Reserve      | 10개
reuters.com               | Federal Reserve      | 10개
finance.yahoo.com         | earnings             | 10개
cnbc.com                  | earnings             | 10개
marketwatch.com           | earnings             | 10개
barrons.com               | earnings             | 10개
fortune.com               | earnings             | 10개
forbes.com                | earnings             | 10개
businessinsider.com       | earnings             | 10개
cnn.com                   | earnings             | 10개
foxbusiness.com           | earnings             | 10개
benzinga.com              | earnings             | 10개
thestreet.com             | earnings             | 10개
fool.com                  | earnings             | 10개
seekingalpha.com          | earnings             | 10개
investing.com             | earnings             | 10개
zacks.com                 | earnings             | 10개
bloomberg.com             | earnings             | 10개
wsj.com                   | earnings             | 10개
ft.com                    | earnings             | 10개
reuters.com               | earnings             | 10개
finance.yahoo.com         | NVIDIA               | 10개
cnbc.com                  | NVIDIA               | 10개
marketwatch.com           | NVIDIA               | 10개
barrons.com               | NVIDIA               | 10개
fortune.com               | NVIDIA               | 10개
forbes.com                | NVIDIA               | 10개
businessinsider.com       | NVIDIA               | 10개
cnn.com                   | NVIDIA               | 6개
benzinga.com              | NVIDIA               | 10개
thestreet.com             | NVIDIA               | 6개
seekingalpha.com          | NVIDIA               | 10개
investing.com             | NVIDIA               | 10개
zacks.com                 | NVIDIA               | 10개
bloomberg.com             | NVIDIA               | 10개
wsj.com                   | NVIDIA               | 10개
ft.com                    | NVIDIA               | 10개
reuters.com               | NVIDIA               | 10개
cnn.com                   | Federal Reserve      | 1개
foxbusiness.com           | Federal Reserve      | 1개
apnews.com                | Federal Reserve      | 2개
apnews.com                | earnings             | 2개
foxbusiness.com           | NVIDIA               | 1개
apnews.com                | NVIDIA               | 1개

총 테스트 기사 수: 893

In [19]:
def crawl_article_for_test(
    article,
    session,
    timeout=15,
    min_body_length=300,
):
    url = article["original_url"]

    try:
        response = session.get(
            url,
            timeout=timeout,
            allow_redirects=True,
        )

    except requests.Timeout:
        return {
            "crawl_status": "TIMEOUT",
            "http_status": None,
            "body_length": 0,
            "body": None,
            "crawl_error": "Request timeout",
        }

    except requests.RequestException as e:
        return {
            "crawl_status": "REQUEST_ERROR",
            "http_status": None,
            "body_length": 0,
            "body": None,
            "crawl_error": f"{type(e).__name__}: {e}",
        }

    status = response.status_code

    # HTTP 오류
    if status != 200:
        return {
            "crawl_status": f"HTTP_{status}",
            "http_status": status,
            "body_length": 0,
            "body": None,
            "crawl_error": f"HTTP {status}",
        }

    # HTML이 아닌 경우
    content_type = response.headers.get(
        "Content-Type",
        "",
    ).lower()

    if "html" not in content_type:
        return {
            "crawl_status": "NOT_HTML",
            "http_status": status,
            "body_length": 0,
            "body": None,
            "crawl_error": f"Content-Type: {content_type}",
        }

    try:
        body = extract(
            response.text,
            url=response.url,
            include_comments=False,
            include_tables=False,
        )

    except Exception as e:
        return {
            "crawl_status": "EXTRACT_ERROR",
            "http_status": status,
            "body_length": 0,
            "body": None,
            "crawl_error": f"{type(e).__name__}: {e}",
        }

    if not body:
        return {
            "crawl_status": "EXTRACT_FAILED",
            "http_status": status,
            "body_length": 0,
            "body": None,
            "crawl_error": "Trafilatura returned None",
        }

    body = body.strip()
    body_length = len(body)

    # 너무 짧으면 실제 기사 본문이라고 보기 어려움
    if body_length < min_body_length:
        return {
            "crawl_status": "CONTENT_TOO_SHORT",
            "http_status": status,
            "body_length": body_length,
            "body": body,
            "crawl_error": (
                f"Body length < {min_body_length}"
            ),
        }

    return {
        "crawl_status": "SUCCESS",
        "http_status": status,
        "body_length": body_length,
        "body": body,
        "crawl_error": None,
    }

In [20]:
def run_crawlability_test(
    test_articles,
    timeout=15,
    min_body_length=300,
):
    results = []

    session = requests.Session()

    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 "
            "(Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 "
            "(KHTML, like Gecko) "
            "Chrome/140.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
    })

    total = len(test_articles)

    for i, article in enumerate(
        test_articles,
        start=1,
    ):
        result = crawl_article_for_test(
            article=article,
            session=session,
            timeout=timeout,
            min_body_length=min_body_length,
        )

        record = {
            "requested_source": article.get(
                "requested_source"
            ),
            "query": article.get("query"),
            "title": article.get("title"),
            "original_url": article.get(
                "original_url"
            ),
            **result,
        }

        results.append(record)

        print(
            f"[{i}/{total}] "
            f"{article.get('requested_source')} | "
            f"{article.get('query')} | "
            f"{result['crawl_status']} "
            f"({result.get('http_status')})"
        )

    session.close()

    return results

In [21]:
test_results = run_crawlability_test(
    test_articles,
    timeout=15,
    min_body_length=300,
)

[1/893] finance.yahoo.com | stock market | SUCCESS (200)
[2/893] finance.yahoo.com | stock market | SUCCESS (200)
[3/893] finance.yahoo.com | stock market | SUCCESS (200)
[4/893] finance.yahoo.com | stock market | SUCCESS (200)
[5/893] finance.yahoo.com | stock market | SUCCESS (200)
[6/893] finance.yahoo.com | stock market | SUCCESS (200)
[7/893] finance.yahoo.com | stock market | SUCCESS (200)
[8/893] finance.yahoo.com | stock market | SUCCESS (200)
[9/893] finance.yahoo.com | stock market | SUCCESS (200)
[10/893] finance.yahoo.com | stock market | SUCCESS (200)
[11/893] cnbc.com | stock market | SUCCESS (200)
[12/893] cnbc.com | stock market | SUCCESS (200)
[13/893] cnbc.com | stock market | SUCCESS (200)
[14/893] cnbc.com | stock market | SUCCESS (200)
[15/893] cnbc.com | stock market | SUCCESS (200)
[16/893] cnbc.com | stock market | SUCCESS (200)
[17/893] cnbc.com | stock market | CONTENT_TOO_SHORT (200)
[18/893] cnbc.com | stock market | SUCCESS (200)
[19/893] cnbc.com | stock market | SUCCESS (200)
[20/893] cnbc.com | stock market | SUCCESS (200)
[21/893] marketwatch.com | stock market | HTTP_412 (412)
[22/893] marketwatch.com | stock market | HTTP_412 (412)
[23/893] marketwatch.com | stock market | HTTP_401 (401)
[24/893] marketwatch.com | stock market | HTTP_412 (412)
[25/893] marketwatch.com | stock market | HTTP_412 (412)
[26/893] marketwatch.com | stock market | HTTP_401 (401)
[27/893] marketwatch.com | stock market | HTTP_412 (412)
[28/893] marketwatch.com | stock market | HTTP_412 (412)
[29/893] marketwatch.com | stock market | HTTP_412 (412)
[30/893] marketwatch.com | stock market | HTTP_412 (412)
[31/893] barrons.com | stock market | HTTP_412 (412)
[32/893] barrons.com | stock market | HTTP_412 (412)
[33/893] barrons.com | stock market | HTTP_412 (412)
[34/893] barrons.com | stock market | HTTP_401 (401)
[35/893] barrons.com | stock market | HTTP_401 (401)
[36/893] barrons.com | stock market | HTTP_412 (412)
[37/893] barrons.com | stock market | HTTP_412 (412)
[38/893] barrons.com | stock market | HTTP_401 (401)
[39/893] barrons.com | stock market | HTTP_412 (412)
[40/893] barrons.com | stock market | HTTP_401 (401)
[41/893] fortune.com | stock market | SUCCESS (200)
[42/893] fortune.com | stock market | SUCCESS (200)
[43/893] fortune.com | stock market | SUCCESS (200)
[44/893] fortune.com | stock market | SUCCESS (200)
[45/893] fortune.com | stock market | SUCCESS (200)
[46/893] fortune.com | stock market | SUCCESS (200)
[47/893] fortune.com | stock market | SUCCESS (200)
[48/893] fortune.com | stock market | SUCCESS (200)
[49/893] forbes.com | stock market | HTTP_403 (403)
[50/893] forbes.com | stock market | HTTP_403 (403)
[51/893] forbes.com | stock market | HTTP_403 (403)
[52/893] forbes.com | stock market | HTTP_403 (403)
[53/893] forbes.com | stock market | HTTP_403 (403)
[54/893] forbes.com | stock market | HTTP_403 (403)
[55/893] forbes.com | stock market | HTTP_403 (403)
[56/893] forbes.com | stock market | HTTP_403 (403)
[57/893] businessinsider.com | stock market | SUCCESS (200)
[58/893] businessinsider.com | stock market | SUCCESS (200)
[59/893] businessinsider.com | stock market | SUCCESS (200)
[60/893] businessinsider.com | stock market | SUCCESS (200)
[61/893] businessinsider.com | stock market | SUCCESS (200)
[62/893] businessinsider.com | stock market | SUCCESS (200)
[63/893] businessinsider.com | stock market | SUCCESS (200)
[64/893] businessinsider.com | stock market | SUCCESS (200)
[65/893] businessinsider.com | stock market | SUCCESS (200)
[66/893] businessinsider.com | stock market | SUCCESS (200)
[67/893] cnn.com | stock market | SUCCESS (200)
[68/893] cnn.com | stock market | SUCCESS (200)
[69/893] cnn.com | stock market | SUCCESS (200)
[70/893] cnn.com | stock market | SUCCESS (200)
[71/893] cnn.com | stock market | SUCCESS (200)
[72/893] cnn.com | stock market | SUCCESS (200)
[73/893] foxbusiness.com | stock market | SUCCESS (200)
[74/893] foxbusiness.com | stock market | SUCCESS (200)
[75/893] foxbusiness.com | stock market | SUCCESS (200)
[76/893] foxbusiness.com | stock market | SUCCESS (200)
[77/893] foxbusiness.com | stock market | SUCCESS (200)
[78/893] foxbusiness.com | stock market | SUCCESS (200)
[79/893] foxbusiness.com | stock market | SUCCESS (200)
[80/893] foxbusiness.com | stock market | SUCCESS (200)
[81/893] foxbusiness.com | stock market | SUCCESS (200)
[82/893] foxbusiness.com | stock market | SUCCESS (200)
[83/893] apnews.com | stock market | HTTP_403 (403)
[84/893] apnews.com | stock market | HTTP_403 (403)
[85/893] apnews.com | stock market | HTTP_403 (403)
[86/893] apnews.com | stock market | HTTP_403 (403)
[87/893] apnews.com | stock market | HTTP_403 (403)
[88/893] apnews.com | stock market | HTTP_403 (403)
[89/893] apnews.com | stock market | HTTP_403 (403)
[90/893] benzinga.com | stock market | HTTP_403 (403)
[91/893] benzinga.com | stock market | HTTP_403 (403)
[92/893] benzinga.com | stock market | HTTP_403 (403)
[93/893] benzinga.com | stock market | HTTP_403 (403)
[94/893] benzinga.com | stock market | HTTP_403 (403)
[95/893] benzinga.com | stock market | HTTP_403 (403)
[96/893] benzinga.com | stock market | HTTP_403 (403)
[97/893] benzinga.com | stock market | HTTP_403 (403)
[98/893] benzinga.com | stock market | HTTP_403 (403)
[99/893] benzinga.com | stock market | HTTP_403 (403)
[100/893] thestreet.com | stock market | HTTP_403 (403)
[101/893] thestreet.com | stock market | SUCCESS (200)
[102/893] thestreet.com | stock market | HTTP_403 (403)
[103/893] thestreet.com | stock market | HTTP_403 (403)
[104/893] thestreet.com | stock market | SUCCESS (200)
[105/893] thestreet.com | stock market | HTTP_403 (403)
[106/893] thestreet.com | stock market | SUCCESS (200)
[107/893] thestreet.com | stock market | HTTP_403 (403)
[108/893] thestreet.com | stock market | HTTP_403 (403)
[109/893] thestreet.com | stock market | HTTP_403 (403)
[110/893] fool.com | stock market | SUCCESS (200)
[111/893] fool.com | stock market | SUCCESS (200)
[112/893] fool.com | stock market | SUCCESS (200)
[113/893] fool.com | stock market | SUCCESS (200)
[114/893] fool.com | stock market | SUCCESS (200)
[115/893] fool.com | stock market | SUCCESS (200)
[116/893] fool.com | stock market | SUCCESS (200)
[117/893] fool.com | stock market | SUCCESS (200)
[118/893] fool.com | stock market | SUCCESS (200)
[119/893] fool.com | stock market | SUCCESS (200)
[120/893] seekingalpha.com | stock market | HTTP_403 (403)
[121/893] seekingalpha.com | stock market | SUCCESS (200)
[122/893] seekingalpha.com | stock market | HTTP_403 (403)
[123/893] seekingalpha.com | stock market | HTTP_403 (403)
[124/893] seekingalpha.com | stock market | HTTP_403 (403)
[125/893] seekingalpha.com | stock market | HTTP_403 (403)
[126/893] seekingalpha.com | stock market | HTTP_403 (403)
[127/893] seekingalpha.com | stock market | HTTP_403 (403)
[128/893] seekingalpha.com | stock market | HTTP_403 (403)
[129/893] seekingalpha.com | stock market | HTTP_403 (403)
[130/893] investing.com | stock market | HTTP_403 (403)
[131/893] investing.com | stock market | HTTP_403 (403)
[132/893] investing.com | stock market | HTTP_403 (403)
[133/893] investing.com | stock market | HTTP_403 (403)
[134/893] investing.com | stock market | HTTP_403 (403)
[135/893] investing.com | stock market | HTTP_403 (403)
[136/893] investing.com | stock market | HTTP_403 (403)
[137/893] investing.com | stock market | HTTP_403 (403)
[138/893] investing.com | stock market | HTTP_403 (403)
[139/893] investing.com | stock market | HTTP_403 (403)
[140/893] zacks.com | stock market | SUCCESS (200)
[141/893] zacks.com | stock market | SUCCESS (200)
[142/893] zacks.com | stock market | SUCCESS (200)
[143/893] zacks.com | stock market | SUCCESS (200)
[144/893] zacks.com | stock market | SUCCESS (200)
[145/893] zacks.com | stock market | SUCCESS (200)
[146/893] zacks.com | stock market | SUCCESS (200)
[147/893] zacks.com | stock market | SUCCESS (200)
[148/893] zacks.com | stock market | SUCCESS (200)
[149/893] zacks.com | stock market | SUCCESS (200)
[150/893] bloomberg.com | stock market | SUCCESS (200)
[151/893] bloomberg.com | stock market | HTTP_403 (403)
[152/893] bloomberg.com | stock market | HTTP_403 (403)
[153/893] bloomberg.com | stock market | REQUEST_ERROR (None)
[154/893] bloomberg.com | stock market | HTTP_403 (403)
[155/893] bloomberg.com | stock market | HTTP_403 (403)
[156/893] bloomberg.com | stock market | HTTP_403 (403)
[157/893] bloomberg.com | stock market | HTTP_403 (403)
[158/893] bloomberg.com | stock market | HTTP_403 (403)
[159/893] bloomberg.com | stock market | HTTP_403 (403)
[160/893] wsj.com | stock market | HTTP_401 (401)
[161/893] wsj.com | stock market | HTTP_401 (401)
[162/893] wsj.com | stock market | HTTP_401 (401)
[163/893] wsj.com | stock market | HTTP_412 (412)
[164/893] wsj.com | stock market | HTTP_401 (401)
[165/893] wsj.com | stock market | HTTP_401 (401)
[166/893] wsj.com | stock market | HTTP_401 (401)
[167/893] wsj.com | stock market | HTTP_401 (401)
[168/893] wsj.com | stock market | HTTP_401 (401)
[169/893] wsj.com | stock market | HTTP_401 (401)
[170/893] ft.com | stock market | SUCCESS (200)
[171/893] ft.com | stock market | HTTP_403 (403)
[172/893] ft.com | stock market | HTTP_403 (403)
[173/893] ft.com | stock market | SUCCESS (200)
[174/893] ft.com | stock market | HTTP_403 (403)
[175/893] ft.com | stock market | SUCCESS (200)
[176/893] ft.com | stock market | HTTP_403 (403)
[177/893] ft.com | stock market | SUCCESS (200)
[178/893] ft.com | stock market | SUCCESS (200)
[179/893] ft.com | stock market | SUCCESS (200)
[180/893] reuters.com | stock market | HTTP_401 (401)
[181/893] reuters.com | stock market | HTTP_401 (401)
[182/893] reuters.com | stock market | HTTP_401 (401)
[183/893] reuters.com | stock market | HTTP_401 (401)
[184/893] reuters.com | stock market | HTTP_401 (401)
[185/893] reuters.com | stock market | HTTP_401 (401)
[186/893] reuters.com | stock market | HTTP_401 (401)
[187/893] reuters.com | stock market | HTTP_401 (401)
[188/893] reuters.com | stock market | HTTP_401 (401)
[189/893] reuters.com | stock market | HTTP_401 (401)
[190/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[191/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[192/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[193/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[194/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[195/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[196/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[197/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[198/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[199/893] finance.yahoo.com | Wall Street | SUCCESS (200)
[200/893] cnbc.com | Wall Street | SUCCESS (200)
[201/893] cnbc.com | Wall Street | SUCCESS (200)
[202/893] cnbc.com | Wall Street | SUCCESS (200)
[203/893] cnbc.com | Wall Street | SUCCESS (200)
[204/893] cnbc.com | Wall Street | SUCCESS (200)
[205/893] cnbc.com | Wall Street | SUCCESS (200)
[206/893] cnbc.com | Wall Street | SUCCESS (200)
[207/893] cnbc.com | Wall Street | SUCCESS (200)
[208/893] cnbc.com | Wall Street | SUCCESS (200)
[209/893] cnbc.com | Wall Street | SUCCESS (200)
[210/893] marketwatch.com | Wall Street | HTTP_401 (401)
[211/893] marketwatch.com | Wall Street | HTTP_401 (401)
[212/893] marketwatch.com | Wall Street | HTTP_401 (401)
[213/893] marketwatch.com | Wall Street | HTTP_401 (401)
[214/893] marketwatch.com | Wall Street | HTTP_401 (401)
[215/893] marketwatch.com | Wall Street | HTTP_401 (401)
[216/893] marketwatch.com | Wall Street | HTTP_401 (401)
[217/893] marketwatch.com | Wall Street | HTTP_401 (401)
[218/893] marketwatch.com | Wall Street | HTTP_401 (401)
[219/893] marketwatch.com | Wall Street | HTTP_401 (401)
[220/893] barrons.com | Wall Street | SUCCESS (200)
[221/893] barrons.com | Wall Street | HTTP_401 (401)
[222/893] barrons.com | Wall Street | HTTP_401 (401)
[223/893] barrons.com | Wall Street | HTTP_401 (401)
[224/893] barrons.com | Wall Street | HTTP_401 (401)
[225/893] barrons.com | Wall Street | HTTP_401 (401)
[226/893] barrons.com | Wall Street | HTTP_401 (401)
[227/893] barrons.com | Wall Street | HTTP_401 (401)
[228/893] barrons.com | Wall Street | HTTP_401 (401)
[229/893] barrons.com | Wall Street | HTTP_401 (401)
[230/893] fortune.com | Wall Street | SUCCESS (200)
[231/893] fortune.com | Wall Street | SUCCESS (200)
[232/893] fortune.com | Wall Street | NOT_HTML (200)
[233/893] fortune.com | Wall Street | SUCCESS (200)
[234/893] fortune.com | Wall Street | SUCCESS (200)
[235/893] fortune.com | Wall Street | SUCCESS (200)
[236/893] fortune.com | Wall Street | SUCCESS (200)
[237/893] fortune.com | Wall Street | SUCCESS (200)
[238/893] fortune.com | Wall Street | SUCCESS (200)
[239/893] fortune.com | Wall Street | SUCCESS (200)
[240/893] forbes.com | Wall Street | HTTP_403 (403)
[241/893] forbes.com | Wall Street | HTTP_403 (403)
[242/893] forbes.com | Wall Street | HTTP_403 (403)
[243/893] forbes.com | Wall Street | SUCCESS (200)
[244/893] forbes.com | Wall Street | HTTP_403 (403)
[245/893] forbes.com | Wall Street | SUCCESS (200)
[246/893] forbes.com | Wall Street | SUCCESS (200)
[247/893] forbes.com | Wall Street | HTTP_403 (403)
[248/893] forbes.com | Wall Street | HTTP_403 (403)
[249/893] forbes.com | Wall Street | HTTP_403 (403)
[250/893] businessinsider.com | Wall Street | SUCCESS (200)
[251/893] businessinsider.com | Wall Street | SUCCESS (200)
[252/893] businessinsider.com | Wall Street | SUCCESS (200)
[253/893] businessinsider.com | Wall Street | SUCCESS (200)
[254/893] businessinsider.com | Wall Street | SUCCESS (200)
[255/893] businessinsider.com | Wall Street | SUCCESS (200)
[256/893] businessinsider.com | Wall Street | SUCCESS (200)
[257/893] businessinsider.com | Wall Street | SUCCESS (200)
[258/893] businessinsider.com | Wall Street | SUCCESS (200)
[259/893] businessinsider.com | Wall Street | SUCCESS (200)
[260/893] cnn.com | Wall Street | SUCCESS (200)
[261/893] cnn.com | Wall Street | SUCCESS (200)
[262/893] cnn.com | Wall Street | SUCCESS (200)
[263/893] cnn.com | Wall Street | SUCCESS (200)
[264/893] cnn.com | Wall Street | SUCCESS (200)
[265/893] cnn.com | Wall Street | SUCCESS (200)
[266/893] cnn.com | Wall Street | SUCCESS (200)
[267/893] cnn.com | Wall Street | SUCCESS (200)
[268/893] cnn.com | Wall Street | SUCCESS (200)
[269/893] cnn.com | Wall Street | SUCCESS (200)
[270/893] foxbusiness.com | Wall Street | SUCCESS (200)
[271/893] foxbusiness.com | Wall Street | SUCCESS (200)
[272/893] foxbusiness.com | Wall Street | SUCCESS (200)
[273/893] foxbusiness.com | Wall Street | SUCCESS (200)
[274/893] foxbusiness.com | Wall Street | SUCCESS (200)
[275/893] foxbusiness.com | Wall Street | SUCCESS (200)
[276/893] foxbusiness.com | Wall Street | SUCCESS (200)
[277/893] apnews.com | Wall Street | HTTP_403 (403)
[278/893] apnews.com | Wall Street | HTTP_403 (403)
[279/893] apnews.com | Wall Street | HTTP_403 (403)
[280/893] apnews.com | Wall Street | HTTP_403 (403)
[281/893] apnews.com | Wall Street | HTTP_403 (403)
[282/893] apnews.com | Wall Street | HTTP_403 (403)
[283/893] apnews.com | Wall Street | HTTP_403 (403)
[284/893] apnews.com | Wall Street | HTTP_403 (403)
[285/893] apnews.com | Wall Street | HTTP_403 (403)
[286/893] apnews.com | Wall Street | HTTP_403 (403)
[287/893] benzinga.com | Wall Street | HTTP_403 (403)
[288/893] benzinga.com | Wall Street | HTTP_403 (403)
[289/893] benzinga.com | Wall Street | HTTP_403 (403)
[290/893] benzinga.com | Wall Street | HTTP_403 (403)
[291/893] benzinga.com | Wall Street | HTTP_403 (403)
[292/893] benzinga.com | Wall Street | HTTP_403 (403)
[293/893] benzinga.com | Wall Street | HTTP_403 (403)
[294/893] benzinga.com | Wall Street | HTTP_403 (403)
[295/893] benzinga.com | Wall Street | HTTP_403 (403)
[296/893] benzinga.com | Wall Street | HTTP_403 (403)
[297/893] thestreet.com | Wall Street | HTTP_403 (403)
[298/893] thestreet.com | Wall Street | HTTP_403 (403)
[299/893] thestreet.com | Wall Street | HTTP_403 (403)
[300/893] thestreet.com | Wall Street | HTTP_403 (403)
[301/893] thestreet.com | Wall Street | HTTP_403 (403)
[302/893] thestreet.com | Wall Street | HTTP_403 (403)
[303/893] thestreet.com | Wall Street | HTTP_403 (403)
[304/893] thestreet.com | Wall Street | HTTP_403 (403)
[305/893] thestreet.com | Wall Street | HTTP_403 (403)
[306/893] thestreet.com | Wall Street | HTTP_403 (403)
[307/893] fool.com | Wall Street | SUCCESS (200)
[308/893] fool.com | Wall Street | SUCCESS (200)
[309/893] fool.com | Wall Street | SUCCESS (200)
[310/893] fool.com | Wall Street | SUCCESS (200)
[311/893] fool.com | Wall Street | SUCCESS (200)
[312/893] fool.com | Wall Street | SUCCESS (200)
[313/893] fool.com | Wall Street | SUCCESS (200)
[314/893] fool.com | Wall Street | SUCCESS (200)
[315/893] fool.com | Wall Street | SUCCESS (200)
[316/893] fool.com | Wall Street | SUCCESS (200)
[317/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[318/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[319/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[320/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[321/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[322/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[323/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[324/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[325/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[326/893] seekingalpha.com | Wall Street | HTTP_403 (403)
[327/893] investing.com | Wall Street | HTTP_403 (403)
[328/893] investing.com | Wall Street | HTTP_403 (403)
[329/893] investing.com | Wall Street | HTTP_403 (403)
[330/893] investing.com | Wall Street | HTTP_403 (403)
[331/893] investing.com | Wall Street | HTTP_403 (403)
[332/893] investing.com | Wall Street | HTTP_403 (403)
[333/893] investing.com | Wall Street | HTTP_403 (403)
[334/893] investing.com | Wall Street | HTTP_403 (403)
[335/893] investing.com | Wall Street | HTTP_403 (403)
[336/893] investing.com | Wall Street | HTTP_403 (403)
[337/893] zacks.com | Wall Street | SUCCESS (200)
[338/893] zacks.com | Wall Street | SUCCESS (200)
[339/893] zacks.com | Wall Street | SUCCESS (200)
[340/893] zacks.com | Wall Street | SUCCESS (200)
[341/893] zacks.com | Wall Street | SUCCESS (200)
[342/893] zacks.com | Wall Street | SUCCESS (200)
[343/893] zacks.com | Wall Street | SUCCESS (200)
[344/893] zacks.com | Wall Street | SUCCESS (200)
[345/893] zacks.com | Wall Street | SUCCESS (200)
[346/893] zacks.com | Wall Street | SUCCESS (200)
[347/893] bloomberg.com | Wall Street | HTTP_403 (403)
[348/893] bloomberg.com | Wall Street | HTTP_403 (403)
[349/893] bloomberg.com | Wall Street | HTTP_403 (403)
[350/893] bloomberg.com | Wall Street | HTTP_403 (403)
[351/893] bloomberg.com | Wall Street | HTTP_403 (403)
[352/893] bloomberg.com | Wall Street | HTTP_403 (403)
[353/893] bloomberg.com | Wall Street | HTTP_403 (403)
[354/893] bloomberg.com | Wall Street | HTTP_403 (403)
[355/893] bloomberg.com | Wall Street | HTTP_403 (403)
[356/893] bloomberg.com | Wall Street | HTTP_403 (403)
[357/893] wsj.com | Wall Street | HTTP_401 (401)
[358/893] wsj.com | Wall Street | HTTP_401 (401)
[359/893] wsj.com | Wall Street | HTTP_401 (401)
[360/893] wsj.com | Wall Street | HTTP_401 (401)
[361/893] wsj.com | Wall Street | HTTP_401 (401)
[362/893] wsj.com | Wall Street | HTTP_401 (401)
[363/893] wsj.com | Wall Street | HTTP_401 (401)
[364/893] wsj.com | Wall Street | HTTP_401 (401)
[365/893] wsj.com | Wall Street | HTTP_401 (401)
[366/893] wsj.com | Wall Street | HTTP_401 (401)
[367/893] ft.com | Wall Street | HTTP_403 (403)
[368/893] ft.com | Wall Street | HTTP_403 (403)
[369/893] ft.com | Wall Street | HTTP_403 (403)
[370/893] ft.com | Wall Street | SUCCESS (200)
[371/893] ft.com | Wall Street | HTTP_403 (403)
[372/893] ft.com | Wall Street | HTTP_403 (403)
[373/893] ft.com | Wall Street | HTTP_403 (403)
[374/893] ft.com | Wall Street | HTTP_403 (403)

In [22]:
detail_df = pd.DataFrame(test_results)

detail_df

,requested_source,query,title,original_url,crawl_status,http_status,body_length,body,crawl_error
0,finance.yahoo.com,stock market,Annaly Capital Management (NLY) Surpasses Q3 E...,https://finance.yahoo.com/markets/stocks/artic...,SUCCESS,200.0,2734,Annaly Capital Management (NLY) came out with ...,None
1,finance.yahoo.com,stock market,Qualcomm (QCOM) Beats Stock Market Upswing: Wh...,https://finance.yahoo.com/markets/stocks/artic...,SUCCESS,200.0,2706,Qualcomm (QCOM) ended the recent trading sessi...,None
2,finance.yahoo.com,stock market,The Market Is Triggering a Warning Not Seen in...,https://finance.yahoo.com/markets/stocks/artic...,SUCCESS,200.0,2823,The market has posted one of its best-ever str...,None
3,finance.yahoo.com,stock market,Could Quantinuum's Breakthrough Make Its Sell-...,https://finance.yahoo.com/markets/stocks/artic...,SUCCESS,200.0,7426,Key Points \n- Interested in Quantinuum Inc.?...,None
4,finance.yahoo.com,stock market,Trump announces $8 billion for farmers to offs...,https://finance.yahoo.com/markets/article/trum...,SUCCESS,200.0,1986,President Trump announced an $8 billion aid pa...,None
...,...,...,...,...,...,...,...,...,...
888,apnews.com,Federal Reserve,UK inflation rises to highest in almost a year...,https://apnews.com/article/britain-inflation-i...,HTTP_403,403.0,0,None,HTTP 403
889,apnews.com,earnings,Meta Q3 revenue tops estimates and Zuckerberg ...,https://apnews.com/article/meta-earnings-faceb...,HTTP_403,403.0,0,None,HTTP 403
890,apnews.com,earnings,Meta ordered to pay New Mexico $25 billion for...,https://apnews.com/article/facebook-penalty-ca...,HTTP_403,403.0,0,None,HTTP 403
891,foxbusiness.com,NVIDIA,This is the way to deploy the latest Nvidia te...,https://www.foxbusiness.com/video/6407194365112,SUCCESS,200.0,399,Live Now\nAll times eastern\nNOW - 3:30 AM\n3:...,None
892,apnews.com,NVIDIA,Nvidia CEO encourages Europe's lagging AI sect...,https://apnews.com/article/jensen-huang-ai-gtc...,HTTP_403,403.0,0,None,HTTP 403

In [23]:
def make_query_summary(detail_df):

    base = (
        detail_df
        .groupby(
            ["requested_source", "query"]
        )
        .agg(
            total=(
                "crawl_status",
                "size",
            ),
            success=(
                "crawl_status",
                lambda x: (
                    x == "SUCCESS"
                ).sum(),
            ),
            avg_body_length=(
                "body_length",
                lambda x: (
                    x[x > 0].mean()
                    if (x > 0).any()
                    else 0
                ),
            ),
        )
        .reset_index()
    )

    base["success_rate"] = (
        base["success"]
        / base["total"]
    )

    # 상태별 개수
    status_counts = (
        pd.crosstab(
            [
                detail_df["requested_source"],
                detail_df["query"],
            ],
            detail_df["crawl_status"],
        )
        .reset_index()
    )

    summary = base.merge(
        status_counts,
        on=[
            "requested_source",
            "query",
        ],
        how="left",
    )

    return summary.sort_values(
        [
            "requested_source",
            "query",
        ]
    ).reset_index(drop=True)

In [25]:
def make_source_summary(detail_df):

    base = (
        detail_df
        .groupby("requested_source")
        .agg(
            total=(
                "crawl_status",
                "size",
            ),
            success=(
                "crawl_status",
                lambda x: (
                    x == "SUCCESS"
                ).sum(),
            ),
            avg_body_length=(
                "body_length",
                lambda x: (
                    x[x > 0].mean()
                    if (x > 0).any()
                    else 0
                ),
            ),
        )
        .reset_index()
    )

    base["success_rate"] = (
        base["success"]
        / base["total"]
    )

    status_counts = (
        pd.crosstab(
            detail_df["requested_source"],
            detail_df["crawl_status"],
        )
        .reset_index()
    )

    summary = base.merge(
        status_counts,
        on="requested_source",
        how="left",
    )

    return summary.sort_values(
        "success_rate",
        ascending=False,
    ).reset_index(drop=True)

In [24]:
query_summary = make_query_summary(
    detail_df
)

query_summary

,requested_source,query,total,success,avg_body_length,success_rate,CONTENT_TOO_SHORT,HTTP_401,HTTP_403,HTTP_412,NOT_HTML,REQUEST_ERROR,SUCCESS
0,apnews.com,Federal Reserve,2,0,0.000000,0.0,0,0,2,0,0,0,0
1,apnews.com,NVIDIA,1,0,0.000000,0.0,0,0,1,0,0,0,0
2,apnews.com,Wall Street,10,0,0.000000,0.0,0,0,10,0,0,0,0
3,apnews.com,earnings,2,0,0.000000,0.0,0,0,2,0,0,0,0
4,apnews.com,stock market,7,0,0.000000,0.0,0,0,7,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,zacks.com,Federal Reserve,3,3,7137.666667,1.0,0,0,0,0,0,0,3
95,zacks.com,NVIDIA,10,10,4387.000000,1.0,0,0,0,0,0,0,10
96,zacks.com,Wall Street,10,10,4741.900000,1.0,0,0,0,0,0,0,10
97,zacks.com,earnings,10,10,5391.400000,1.0,0,0,0,0,0,0,10
98,zacks.com,stock market,10,10,4086.000000,1.0,0,0,0,0,0,0,10

In [26]:
source_summary = make_source_summary(
    detail_df
)

source_summary

,requested_source,total,success,avg_body_length,success_rate,CONTENT_TOO_SHORT,HTTP_401,HTTP_403,HTTP_412,NOT_HTML,REQUEST_ERROR,SUCCESS
0,zacks.com,43,43,4825.023256,1.000000,0,0,0,0,0,0,43
1,cnn.com,33,33,19772.575758,1.000000,0,0,0,0,0,0,33
2,foxbusiness.com,29,29,2002.034483,1.000000,0,0,0,0,0,0,29
3,fool.com,40,40,19389.575000,1.000000,0,0,0,0,0,0,40
4,businessinsider.com,50,50,6422.240000,1.000000,0,0,0,0,0,0,50
5,finance.yahoo.com,50,50,3463.720000,1.000000,0,0,0,0,0,0,50
6,fortune.com,48,47,4932.021277,0.979167,0,0,0,0,1,0,47
7,cnbc.com,50,48,3708.300000,0.960000,2,0,0,0,0,0,48
8,ft.com,50,31,6342.806452,0.620000,0,0,19,0,0,0,31
9,forbes.com,48,10,4632.909091,0.208333,1,0,37,0,0,0,10
10,thestreet.com,39,4,7362.750000,0.102564,0,0,35,0,0,0,4
11,barrons.com,41,1,1068.000000,0.024390,0,29,0,11,0,0,1
12,bloomberg.com,50,1,1238.000000,0.020000,0,0,48,0,0,1,1
13,seekingalpha.com,50,1,2675.000000,0.020000,0,0,49,0,0,0,1
14,benzinga.com,50,0,0.000000,0.000000,0,0,50,0,0,0,0
15,investing.com,50,0,0.000000,0.000000,0,0,50,0,0,0,0
16,marketwatch.com,50,0,0.000000,0.000000,0,36,0,14,0,0,0
17,reuters.com,50,0,0.000000,0.000000,0,50,0,0,0,0,0
18,wsj.com,50,0,0.000000,0.000000,0,47,0,3,0,0,0
19,apnews.com,22,0,0.000000,0.000000,0,0,22,0,0,0,0

In [27]:
USABLE_THRESHOLD = 0.8

usable_sources = (
    source_summary.loc[
        source_summary["success_rate"]
        >= USABLE_THRESHOLD,
        "requested_source",
    ]
    .tolist()
)

usable_sources

['zacks.com',
 'cnn.com',
 'foxbusiness.com',
 'fool.com',
 'businessinsider.com',
 'finance.yahoo.com',
 'fortune.com',
 'cnbc.com']

In [49]:
SOURCE = {
    # 1순위: 미국 증시/금융 전문
    "finance.yahoo.com": "Yahoo Finance",
    "cnbc.com": "CNBC",
 
    # 2순위: 경제/비즈니스 종합
    "fortune.com": "Fortune",
    "businessinsider.com": "Business Insider",
    "cnn.com": "CNN Business",
    "foxbusiness.com": "Fox Business",

    # 3순위: 투자 전문
    #"benzinga.com": "Benzinga",
    "fool.com": "The Motley Fool",
    "zacks.com": "Zacks",
}

In [1]:
# 딕셔너리의 키값들만 추출하여 필터링
filtered_df = test_results[test_results['requested_source'].isin(SOURCE.keys())]

NameError: name 'test_results' is not defined

In [ ]:
for index, row in filtered_df.iterrows():
    print(f"--- 행 번호: {index} ---")
    print(f"언론사: {row['requested_source']}")
    print(f"제목: {row['title']}")
    print(f"URL: {row['original_url']}")
    print(f"본문 일부: {str(row['body'])[:500]}...") # 본문이 길므로 앞 100자만 출력
    print("\n" + "="*50 + "\n")