```Plain Text
https://sdmx.oecd.org/public/rest/data/
{AGENCY},{DATAFLOW},{VERSION}/{SELECTION}
?startPeriod=...
&endPeriod=...
&dimensionAtObservation=AllDimensions
&format=csvfilewithlabels
```

In [1]:
import requests
import pandas as pd
from io import StringIO

url = (
    "https://sdmx.oecd.org/public/rest/data/"
    "OECD.SDD.STES,DSD_STES@DF_CLI/"
    ".M.LI...AA...H"
    "?startPeriod=2023-02"
    "&dimensionAtObservation=AllDimensions"
    "&format=csvfilewithlabels"
)

response = requests.get(url)
response.raise_for_status()

df = pd.read_csv(StringIO(response.text))

df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,FREQ,Frequency of observation,MEASURE,Measure,...,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals,BASE_PER,Base period
0,DATAFLOW,OECD.SDD.STES:DSD_STES@DF_CLI(4.1),Composite leading indicators,I,A5M,Major five Asia economies,M,Monthly,LI,Composite leading indicator (CLI),...,100.52290,NaN,A,Normal value,0,Units,2,Two,NaN,NaN
1,DATAFLOW,OECD.SDD.STES:DSD_STES@DF_CLI(4.1),Composite leading indicators,I,A5M,Major five Asia economies,M,Monthly,LI,Composite leading indicator (CLI),...,100.56200,NaN,A,Normal value,0,Units,2,Two,NaN,NaN
2,DATAFLOW,OECD.SDD.STES:DSD_STES@DF_CLI(4.1),Composite leading indicators,I,AUS,Australia,M,Monthly,LI,Composite leading indicator (CLI),...,98.56926,NaN,A,Normal value,0,Units,2,Two,NaN,NaN
3,DATAFLOW,OECD.SDD.STES:DSD_STES@DF_CLI(4.1),Composite leading indicators,I,AUS,Australia,M,Monthly,LI,Composite leading indicator (CLI),...,98.63730,NaN,A,Normal value,0,Units,2,Two,NaN,NaN
4,DATAFLOW,OECD.SDD.STES:DSD_STES@DF_CLI(4.1),Composite leading indicators,I,A5M,Major five Asia economies,M,Monthly,LI,Composite leading indicator (CLI),...,100.03020,NaN,A,Normal value,0,Units,2,Two,NaN,NaN

In [2]:
import requests
import pandas as pd
from io import StringIO


# ============================================================
# 1. 조회 조건
# ============================================================

START_YEAR = 2000
END_YEAR = 2025

# OECD National Accounts at a Glance - Chapter 1: GDP
BASE_URL = (
    "https://sdmx.oecd.org/public/rest/data/"
    "OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/"
)

# SDMX key
#
# A                  : Annual
# KOR+USA            : Korea + United States
# B1GQ_R_GR          : Real gross domestic product growth rate
# ..                 : 나머지 차원은 해당 지표에 대응되는 값 사용
#
SDMX_KEY = "A.KOR+USA.B1GQ_R_GR.."

url = (
    f"{BASE_URL}{SDMX_KEY}"
    f"?startPeriod={START_YEAR}"
    f"&endPeriod={END_YEAR}"
    f"&dimensionAtObservation=AllDimensions"
    f"&format=csvfilewithlabels"
)

print("요청 URL:")
print(url)

요청 URL:
https://sdmx.oecd.org/public/rest/data/OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/A.KOR+USA.B1GQ_R_GR..?startPeriod=2000&endPeriod=2025&dimensionAtObservation=AllDimensions&format=csvfilewithlabels

In [3]:
response = requests.get(
    url,
    headers={
        "User-Agent": "Mozilla/5.0"
    },
    timeout=60
)

response.raise_for_status()

df = pd.read_csv(StringIO(response.text))

print("데이터 크기:", df.shape)
display(df.head())

데이터 크기: (52, 64)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency of observation,REF_AREA,Reference area,MEASURE,Measure,...,CONF_STATUS,Confidentiality status,DECIMALS,Decimals,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,CURRENCY,Currency
0,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
1,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,USA,United States,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
2,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
3,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,USA,United States,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
4,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable

In [4]:
print("전체 칼럼 수:", len(df.columns))

for i, col in enumerate(df.columns, start=1):
    print(f"{i:2d}. {col}")

전체 칼럼 수: 64
 1. STRUCTURE
 2. STRUCTURE_ID
 3. STRUCTURE_NAME
 4. ACTION
 5. FREQ
 6. Frequency of observation
 7. REF_AREA
 8. Reference area
 9. MEASURE
10. Measure
11. UNIT_MEASURE
12. Unit of measure
13. CHAPTER
14. Chapter
15. TIME_PERIOD
16. Time period
17. OBS_VALUE
18. Observation value
19. ADJUSTMENT
20. Adjustment
21. COUNTERPART_AREA
22. Counterpart area
23. SECTOR
24. Institutional sector
25. COUNTERPART_SECTOR
26. Counterpart institutional sector
27. CONSOLIDATION
28. Consolidation status
29. ACCOUNTING_ENTRY
30. Accounting entry
31. TRANSACTION
32. Transaction
33. INSTR_ASSET
34. Instruments and assets
35. MATURITY
36. Original and residual maturity
37. PRODUCT
38. Product
39. PENSION_FUNDTYPE
40. Pension fund type
41. CURRENCY_DENOM
42. Currency of denomination
43. VALUATION
44. Valuation
45. PRICE_BASE
46. Price base
47. TRANSFORMATION
48. Transformation
49. TABLE_IDENTIFIER
50. Table identifier
51. REF_YEAR_PRICE
52. Price reference year
53. BASE_PER
54. Base period
55. CONF_STATUS
56. Confidentiality status
57. DECIMALS
58. Decimals
59. OBS_STATUS
60. Observation status
61. UNIT_MULT
62. Unit multiplier
63. CURRENCY
64. Currency

In [5]:
important_columns = [
    "FREQ",
    "REF_AREA",
    "MEASURE",
    "UNIT_MEASURE",
    "PRICE_BASE",
    "TRANSACTION",
    "TRANSFORMATION",
    "TIME_PERIOD",
    "OBS_VALUE",
    "OBS_STATUS",
]

important_columns = [
    col for col in important_columns
    if col in df.columns
]

display(df[important_columns].head(20))

,FREQ,REF_AREA,MEASURE,UNIT_MEASURE,PRICE_BASE,TRANSACTION,TRANSFORMATION,TIME_PERIOD,OBS_VALUE,OBS_STATUS
0,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2000,9.201858,A
1,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2000,4.077586,A
2,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2001,4.725936,A
3,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2001,0.955538,A
4,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2002,7.743999,A
5,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2002,1.700447,A
6,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2003,3.074727,A
7,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2003,2.795606,A
8,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2004,5.183637,A
9,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2004,3.847772,A
10,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2005,4.358237,A
11,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2005,3.483550,A
12,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2006,5.245006,A
13,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2006,2.784540,A
14,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2007,5.841963,A
15,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2007,2.003858,A
16,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2008,3.004405,A
17,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2008,0.113587,A
18,A,KOR,B1GQ_R_GR,PC,L,B1GQ,G1,2009,0.819862,A
19,A,USA,B1GQ_R_GR,PC,L,B1GQ,G1,2009,-2.576500,A

In [6]:
check_columns = [
    "FREQ",
    "MEASURE",
    "UNIT_MEASURE",
    "PRICE_BASE",
    "TRANSACTION",
    "TRANSFORMATION",
]

for col in check_columns:
    if col in df.columns:
        values = df[col].dropna().unique()

        print(f"{col}: {values}")

        if len(values) != 1:
            print(
                f"  ⚠️ {col}에 여러 값이 존재합니다. "
                "한국과 미국을 직접 비교하기 전에 확인이 필요합니다."
            )

FREQ: ['A']
MEASURE: ['B1GQ_R_GR']
UNIT_MEASURE: ['PC']
PRICE_BASE: ['L']
TRANSACTION: ['B1GQ']
TRANSFORMATION: ['G1']

In [7]:
same_condition_columns = [
    "FREQ",
    "MEASURE",
    "UNIT_MEASURE",
    "PRICE_BASE",
    "TRANSACTION",
    "TRANSFORMATION",
]

for col in same_condition_columns:
    if col not in df.columns:
        continue

    unique_values = df[col].dropna().unique()

    if len(unique_values) != 1:
        raise ValueError(
            f"{col} 기준이 하나로 통일되어 있지 않습니다: "
            f"{unique_values}"
        )

print("✅ 한국과 미국 데이터의 주요 단위·기준이 동일합니다.")

✅ 한국과 미국 데이터의 주요 단위·기준이 동일합니다.

In [8]:
countries = set(df["REF_AREA"].dropna().unique())

expected_countries = {"KOR", "USA"}

if countries != expected_countries:
    raise ValueError(
        f"예상 국가와 실제 국가가 다릅니다.\n"
        f"예상: {expected_countries}\n"
        f"실제: {countries}"
    )

print("✅ KOR, USA 데이터가 모두 존재합니다.")

✅ KOR, USA 데이터가 모두 존재합니다.

In [9]:
label_columns = [
    "Reference area",
    "Measure",
    "Unit of measure",
    "Frequency of observation",
    "Price base",
    "Time period",
    "Observation value",
]

for col in label_columns:
    if col in df.columns:
        print(f"\n[{col}]")
        print(df[col].dropna().unique()[:10])

[Reference area]
['Korea' 'United States']

[Measure]
['Real gross domestic product growth rate']

[Unit of measure]
['Percentage change']

[Frequency of observation]
['Annual']

[Price base]
['Chain linked volume']

[Time period]
[]

[Observation value]
[]

In [10]:
gdp = df[
    [
        "REF_AREA",
        "TIME_PERIOD",
        "OBS_VALUE",
        "MEASURE",
        "UNIT_MEASURE",
        "PRICE_BASE",
        "FREQ",
    ]
].copy()

gdp["OBS_VALUE"] = pd.to_numeric(
    gdp["OBS_VALUE"],
    errors="coerce"
)

gdp["TIME_PERIOD"] = pd.to_numeric(
    gdp["TIME_PERIOD"],
    errors="coerce"
)

gdp = (
    gdp
    .dropna(subset=["TIME_PERIOD", "OBS_VALUE"])
    .sort_values(["TIME_PERIOD", "REF_AREA"])
    .reset_index(drop=True)
)

display(gdp.head(20))

   REF_AREA  TIME_PERIOD  OBS_VALUE    MEASURE UNIT_MEASURE PRICE_BASE FREQ
0       KOR         2000   9.201858  B1GQ_R_GR           PC          L    A
1       USA         2000   4.077586  B1GQ_R_GR           PC          L    A
2       KOR         2001   4.725936  B1GQ_R_GR           PC          L    A
3       USA         2001   0.955538  B1GQ_R_GR           PC          L    A
4       KOR         2002   7.743999  B1GQ_R_GR           PC          L    A
5       USA         2002   1.700447  B1GQ_R_GR           PC          L    A
6       KOR         2003   3.074727  B1GQ_R_GR           PC          L    A
7       USA         2003   2.795606  B1GQ_R_GR           PC          L    A
8       KOR         2004   5.183637  B1GQ_R_GR           PC          L    A
9       USA         2004   3.847772  B1GQ_R_GR           PC          L    A
10      KOR         2005   4.358237  B1GQ_R_GR           PC          L    A
11      USA         2005   3.483550  B1GQ_R_GR           PC          L    A
12      KOR         2006   5.245006  B1GQ_R_GR           PC          L    A
13      USA         2006   2.784540  B1GQ_R_GR           PC          L    A
14      KOR         2007   5.841963  B1GQ_R_GR           PC          L    A
15      USA         2007   2.003858  B1GQ_R_GR           PC          L    A
16      KOR         2008   3.004405  B1GQ_R_GR           PC          L    A
17      USA         2008   0.113587  B1GQ_R_GR           PC          L    A
18      KOR         2009   0.819862  B1GQ_R_GR           PC          L    A
19      USA         2009  -2.576500  B1GQ_R_GR           PC          L    A

In [11]:
comparison = (
    gdp
    .pivot(
        index="TIME_PERIOD",
        columns="REF_AREA",
        values="OBS_VALUE"
    )
    .rename(
        columns={
            "KOR": "Korea",
            "USA": "United States",
        }
    )
    .reset_index()
)

comparison.columns.name = None

display(comparison)

    TIME_PERIOD     Korea  United States
0          2000  9.201858       4.077586
1          2001  4.725936       0.955538
2          2002  7.743999       1.700447
3          2003  3.074727       2.795606
4          2004  5.183637       3.847772
5          2005  4.358237       3.483550
6          2006  5.245006       2.784540
7          2007  5.841963       2.003858
8          2008  3.004405       0.113587
9          2009  0.819862      -2.576500
10         2010  6.981661       2.695193
11         2011  3.688032       1.564407
12         2012  2.547666       2.289113
13         2013  3.291396       2.117830
14         2014  3.214680       2.523820
15         2015  2.920293       2.945550
16         2016  3.171527       1.819451
17         2017  3.433192       2.457622
18         2018  3.176116       2.966505
19         2019  2.313802       2.583825
20         2020 -0.700242      -2.081376
21         2021  4.696525       6.152022
22         2022  2.908638       2.524214
23         2023  1.482495       2.934363
24         2024  2.193146       2.793187
25         2025  1.139040       2.161382

In [12]:
import requests
import pandas as pd
from io import StringIO


def get_oecd_kor_usa_real_gdp_growth(
    start_year=2000,
    end_year=2025,
):
    base_url = (
        "https://sdmx.oecd.org/public/rest/data/"
        "OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/"
    )

    # Annual / KOR+USA / Real GDP growth rate
    sdmx_key = "A.KOR+USA.B1GQ_R_GR.."

    url = (
        f"{base_url}{sdmx_key}"
        f"?startPeriod={start_year}"
        f"&endPeriod={end_year}"
        f"&dimensionAtObservation=AllDimensions"
        f"&format=csvfilewithlabels"
    )

    response = requests.get(
        url,
        headers={"User-Agent": "Mozilla/5.0"},
        timeout=60,
    )
    response.raise_for_status()

    df = pd.read_csv(StringIO(response.text))

    if df.empty:
        raise ValueError("OECD API에서 데이터가 반환되지 않았습니다.")

    # --------------------------------------------------------
    # 국가 확인
    # --------------------------------------------------------
    countries = set(df["REF_AREA"].dropna().unique())

    expected_countries = {"KOR", "USA"}

    if countries != expected_countries:
        raise ValueError(
            f"국가가 예상과 다릅니다: {countries}"
        )

    # --------------------------------------------------------
    # 비교 기준 동일 여부 확인
    # --------------------------------------------------------
    comparison_dimensions = [
        "FREQ",
        "MEASURE",
        "UNIT_MEASURE",
        "PRICE_BASE",
        "TRANSACTION",
        "TRANSFORMATION",
    ]

    metadata = {}

    for col in comparison_dimensions:

        if col not in df.columns:
            continue

        values = df[col].dropna().unique().tolist()

        metadata[col] = values

        if len(values) != 1:
            raise ValueError(
                f"{col} 값이 하나로 통일되어 있지 않습니다: "
                f"{values}"
            )

    # --------------------------------------------------------
    # 필요한 칼럼
    # --------------------------------------------------------
    result = df[
        [
            "REF_AREA",
            "TIME_PERIOD",
            "OBS_VALUE",
            "FREQ",
            "MEASURE",
            "UNIT_MEASURE",
            "PRICE_BASE",
        ]
    ].copy()

    result["TIME_PERIOD"] = pd.to_numeric(
        result["TIME_PERIOD"],
        errors="coerce",
    )

    result["OBS_VALUE"] = pd.to_numeric(
        result["OBS_VALUE"],
        errors="coerce",
    )

    result = (
        result
        .dropna(subset=["TIME_PERIOD", "OBS_VALUE"])
        .sort_values(["TIME_PERIOD", "REF_AREA"])
        .reset_index(drop=True)
    )

    # --------------------------------------------------------
    # 비교용 wide table
    # --------------------------------------------------------
    comparison = (
        result
        .pivot(
            index="TIME_PERIOD",
            columns="REF_AREA",
            values="OBS_VALUE",
        )
        .rename(
            columns={
                "KOR": "Korea",
                "USA": "United States",
            }
        )
        .reset_index()
    )

    comparison.columns.name = None

    return df, result, comparison, metadata, url

In [13]:
raw_df, gdp_df, comparison_df, metadata, url = (
    get_oecd_kor_usa_real_gdp_growth(
        start_year=2000,
        end_year=2025,
    )
)

In [14]:
metadata

{'FREQ': ['A'],
 'MEASURE': ['B1GQ_R_GR'],
 'UNIT_MEASURE': ['PC'],
 'PRICE_BASE': ['L'],
 'TRANSACTION': ['B1GQ'],
 'TRANSFORMATION': ['G1']}

In [15]:
raw_df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency of observation,REF_AREA,Reference area,MEASURE,Measure,...,CONF_STATUS,Confidentiality status,DECIMALS,Decimals,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,CURRENCY,Currency
0,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
1,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,USA,United States,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
2,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
3,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,USA,United States,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable
4,DATAFLOW,OECD.SDD.NAD:DSD_NAAG@DF_NAAG_I(1.0),NAAG Chapter 1: GDP,I,A,Annual,KOR,Korea,B1GQ_R_GR,Real gross domestic product growth rate,...,F,Free (free for publication),2,Two,A,Normal value,0,Units,_Z,Not applicable

In [16]:
gdp_df.head()

  REF_AREA  TIME_PERIOD  OBS_VALUE FREQ    MEASURE UNIT_MEASURE PRICE_BASE
0      KOR         2000   9.201858    A  B1GQ_R_GR           PC          L
1      USA         2000   4.077586    A  B1GQ_R_GR           PC          L
2      KOR         2001   4.725936    A  B1GQ_R_GR           PC          L
3      USA         2001   0.955538    A  B1GQ_R_GR           PC          L
4      KOR         2002   7.743999    A  B1GQ_R_GR           PC          L

In [17]:
comparison_df

    TIME_PERIOD     Korea  United States
0          2000  9.201858       4.077586
1          2001  4.725936       0.955538
2          2002  7.743999       1.700447
3          2003  3.074727       2.795606
4          2004  5.183637       3.847772
5          2005  4.358237       3.483550
6          2006  5.245006       2.784540
7          2007  5.841963       2.003858
8          2008  3.004405       0.113587
9          2009  0.819862      -2.576500
10         2010  6.981661       2.695193
11         2011  3.688032       1.564407
12         2012  2.547666       2.289113
13         2013  3.291396       2.117830
14         2014  3.214680       2.523820
15         2015  2.920293       2.945550
16         2016  3.171527       1.819451
17         2017  3.433192       2.457622
18         2018  3.176116       2.966505
19         2019  2.313802       2.583825
20         2020 -0.700242      -2.081376
21         2021  4.696525       6.152022
22         2022  2.908638       2.524214
23         2023  1.482495       2.934363
24         2024  2.193146       2.793187
25         2025  1.139040       2.161382

In [18]:
print(url)

https://sdmx.oecd.org/public/rest/data/OECD.SDD.NAD,DSD_NAAG@DF_NAAG_I,1.0/A.KOR+USA.B1GQ_R_GR..?startPeriod=2000&endPeriod=2025&dimensionAtObservation=AllDimensions&format=csvfilewithlabels